### ISSUE TITLE
"Entities" tab is not necessary

### ISSUE THREAD

**Issue by Jcen902** [kblincoe/QualOpt_SE701#112]
When sign in as admin, there is a tab called "Entities" which provide two options: "studies" and "participants", but there is "Studies" and "Participants" tab already, so "Entities" tab is not necessary.

@softeng-701 This is a small issue

**Comment by softeng-701** [comment]
@Jcen902 APPROVED!

**Comment by Jcen902** [comment]
Still no one want it? Ok, I will take it, should be a easy fix...
