### ISSUE TITLE
Fix different display format of buttons on study page

### ISSUE THREAD

**Issue by softeng-701** [kblincoe/QualOpt_SE701#16]
On the overall study page, there are three buttons at the end of each individual study (View, Edit, Delete). If you go into an individual study these three buttons are replicated in a similar manner but with slightly different purposes (they are instead: Back, Edit, Send). 

However, the buttons are displayed in different ways on each of the pages. The overall study page buttons are joined together and the individual study page buttons are separated. These buttons should be displayed in similar ways to provide unity to the program.

**Comment by FMcIntosh** [comment]
Claiming
