### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by softeng-701** [kblincoe/QualOpt_SE701#18]
Currently at the bottom of every page is "Created by Fraser and Dinal". This needs to be replaced with the University of Auckland. 

Then on the information page add an about section saying that the project was originally worked on by Fraser Lewis-Smith and Dinal Wanniarachchi, was further developed by the students of SoftEng 701, and was all under the supervision of Dr Kelly Blincoe.

**Comment by oliver-allen** [comment]
Claiming this issue

**Comment by sidpartha1** [comment]
claiming
