### ISSUE TITLE
Split study creation in to seperate pages

### ISSUE THREAD

**Issue by softeng-701** [kblincoe/QualOpt_SE701#33]
Currently, all the information for a study is entered on a single page. This means that the input boxes are all smaller than what the user might require. This is especially true for the email input box.

To improve the workflow, the email information input should be moved to another screen following on after you have entered the study details.

**Comment by jsoulsby** [comment]
I'll be taking a look at this.

**Comment by JGud007** [comment]
@jsoulsby this may have some dependency to my issue #11 as I will be making separate create and edit pages for studies to allow for the different titles my issue requires

**Comment by JGud007** [comment]
@jsoulsby ignore my last comment that was a bad way of fixing my issue so am doing it differently now shouldn't affect you

**Comment by jsoulsby** [comment]
@softeng-701 Instead of shifting the 'Email' section of the modal into a separate page, how do you feel about splitting it vertically into two sections?

This will keep all information relevant to creating a new study on one page and should increase the size of input text boxes as well.
