### ISSUE TITLE
Typo in readme.md

### ISSUE THREAD

**Issue by xavier630** [kblincoe/QualOpt_SE701#46]
There is a typo currently in the readme.md.

![image](https://user-images.githubusercontent.com/9077250/37011872-ea99dc24-2156-11e8-854e-1963c40a6289.png)

**Comment by xavier630** [comment]
Solving it now.

**Comment by xavier630** [comment]
@softeng-701

**Comment by xavier630** [comment]
Also, I tried to add a label but had no success. Perhaps I lack permissions.

**Comment by TheGuardianWolf** [comment]
You will have to wait for approval on the issue before it can be 'assigned'

**Comment by wilmol** [comment]
Another typo in README.md
![ziv5d9e](https://user-images.githubusercontent.com/18110897/37021186-923bf274-2183-11e8-9055-909b96dc5ce0.png)

**Comment by xavier630** [comment]
@lathakarthigaa Yep, I tried to add the size as a label when I created it but didn't seem to have permission. I'll specify it in the comments next time.
