### ISSUE TITLE
mvnw is CRLF instead of LF, preventing the script from running in docker

### ISSUE THREAD

**Issue by TheGuardianWolf** [kblincoe/QualOpt_SE701#51]
I couldn't get this script to actually run in a docker container till I fixed this, so this minor issue should probably be fixed and updated in .gitattributes?

**Comment by TheGuardianWolf** [comment]
@softeng-701

**Comment by lathakarthigaa** [comment]
@TheGuardianWolf very-small?

**Comment by TheGuardianWolf** [comment]
Yes, I'll submit the pull request shortly

**Comment by TheGuardianWolf** [comment]
#62
