### ISSUE TITLE
Sign in button on the homepage

### ISSUE THREAD

**Issue by JGud007** [kblincoe/QualOpt_SE701#69]
On the homepage add a button to sign in somewhere. Currently you need to click into the account drop-down and then select sign in. It would be more user friendly to have sign in button somewhere obvious on the homepage to allow a non logged in user to log in. This button should not be present on the homepage if the user is logged in. 

This would relate to issue #30 Redesign Home page

This would be a **small/very-small** feature/issue to implement

**Comment by umih874** [comment]
It seems like there is already a login function on the home page in form of a hyperlink. This should just be turned into a button. I would be moving this around in regard to #30 issue.

**Comment by JGud007** [comment]
@umih874 wow I never even realised that was a hyperlink! if your already working on this in #30 I will close the issue.

**Comment by softeng-701** [comment]
@JGud007 you are right, we have to close this issue! Thanks.
