### ISSUE TITLE
Typos in About page

### ISSUE THREAD

**Issue by dylHall** [kblincoe/QualOpt_SE701#70]
Just had a quick look through the About page, and identified a few typos in the "About the project" section.

"QaulOpt" and "Qual opt" should be switched to "QualOpt."

@softeng-701 Since the routing and page have already been set up, it would just be an easy **very-small** task just to fix these typos!

**Comment by kblincoe** [comment]
Are there other typos or is this the only one?

**Comment by dylHall** [comment]
Had another look and "recieve" is also a typo which is used twice on the page (and potentially "customise" to customize).

Note: these are also misspelled on the home page of QualOpt as well.

**Comment by kblincoe** [comment]
Please fix in issue #29
