### ISSUE TITLE
Fix Send Invitation button

### ISSUE THREAD

**Issue by wilmol** [kblincoe/QualOpt_SE701#71]
@pulkitkalra and I have this problem.

Currently, the Send Invitation button on the view single study screen doesn't send emails to the participants. This needs to be fixed for #26 and #36.

Will need to investigate further but I think the logic is there just not linked to the button so small issue.
@softeng-701 

Update: I don't think the API had support for sending studies so I created a new endpoint then linked that to the button. This was more work than initially thought; I think medium issue.

**Comment by wilmol** [comment]
@pulkitkalra the button now has some functionality although there is an authentication problem. However, I don't think it blocks #26 anymore.

**Comment by wilmol** [comment]
@softeng-701 this was merged without the size being set. Can I confirm it was medium?

**Comment by softeng-701** [comment]
@wilmol size label added now!
