### ISSUE TITLE
Remove 'Go To Studies' Button from homepage when not logged in

### ISSUE THREAD

**Issue by FMcIntosh** [kblincoe/QualOpt_SE701#81]
Currently, there is a button labelled 'Go To Studies' that is visible on the homepage whether the user is logged in or not. When the user is not logged in, clicking this button goes to an Error Page, with a popover that has the log in options.

There are a couple of options, but it seems clear that there is no point the user being able to go to their studies when they are not logged in because this sends them to an error page. The most sensible option seems to be replacing the 'Go To Studies' button with a login button when the user has not logged in. This ties in to #69 which is about adding a login button to the home page. However, even if the login button is displayed somewhere else, there should not be a 'Go To Studies' option displayed until the user has logged in.

This issue is somewhere between a small and a very-small depending on the solution that is decided upon.

**Comment by umih874** [comment]
I would be removing this button completely as a part of #30 issue. The user can access studies through the drop-down menu once they log in. So maybe we don't need to worry about this issue?

**Comment by softeng-701** [comment]
@FMcIntosh As per @umih874, can we close this issue?

**Comment by FMcIntosh** [comment]
@softeng-701 Yes if the button is being removed this can be closed. Cheers @umih874
