### ISSUE TITLE
Warning in yarn start process

### ISSUE THREAD

**Issue by TheGuardianWolf** [kblincoe/QualOpt_SE701#94]
Remove the double dash from the webpack-dev-server script for yarn to suppress warning.

```
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
```

Size is very small @softeng-701 .

**Comment by softeng-701** [comment]
@TheGuardianWolf Do you think it takes an hour to finish to claim as very-small?

**Comment by TheGuardianWolf** [comment]
Not really, we can 'merge' this one with #106

**Comment by softeng-701** [comment]
@TheGuardianWolf Awesome! I will close this one!
